languageCode = "en"
languageName = "English"
weight = 1
title = "Writing the fog..."

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = ""
  description = "Adventures in Social Anatomy."

[params.author]
  name = "Liminal Recursions"
  email = ""
  image = "img/avatar.png"
  headline = "Adventures in Social Anatomy."
  bio = ""
  links = [
    { storygraph = "https://app.thestorygraph.com/profile/thesliceiest"},
    
  ]
