baseURL = 'https://www.liminalrecursions.com/'
languageCode = 'en-us'
title = 'Liminal Recursions'
theme = "stack"

[pagination]
pagerSize = 10

[params]
mainSections = ["posts"]
description = "Adventures in Social Anatomy"

[params.sidebar]
emoji = "ðŸŒ€"
subtitle = "Adventures in Social Anatomy"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/profile.jpg"

[params.footer]
since = 2025
customText = "Â©2025 liminalrecursions"

[params.comments]
enabled = true
provider = "giscus"

[params.comments.giscus]
repo = "intraventions/writing"
repoID = "R_kgDOQjxv3g"
category = "General"
categoryID = "<your-category-id>"
mapping = "pathname"
reactionsEnabled = true
emitMetadata = false
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "en"

# Menu 

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3
[menu.main.params]
icon = "tag"
