baseURL = 'https://www.liminalrecursions.com/'
languageCode = 'en-us'
title = 'Liminal Recursions'
theme = ["PaperMod"]

mainSections = ["posts"]

#Categories
category = "categories"
tag = "tags"

[params]

# Profile section (optional)
[params.profileMode]
enabled = true
title = "Liminal Recursions"
subtitle = "Adventures in Social Anatomy"
imageUrl = "/images/profile.png"      # put your image in static/images/
imageTitle = "Profile Image"
imageWidth = 240
imageHeight = 240

[[params.profileMode.buttons]]
name = "Archive"
url = "/posts/"


# Comments
comments = true   # enables comments globally

[params.giscus]     # Giscus settings
repo = "intraventions/writing"
repoID = "R_kgDOQjxv3g"
category = "General"
categoryID = "<your-category-id>"
mapping = "pathname"
reactionsEnabled = true
emitMetadata = false
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "en"
crossorigin = "anonymous"

# Theme appearance
defaultTheme = "auto"        # auto dark/light
ShowReadingTime = true        # show reading time on posts
ShowShareButtons = true       # social share buttons
ShowPostNavLinks = true       # next/prev post links
ShowBreadCrumbs = true        # breadcrumbs on posts
ShowCodeCopyButtons = true    # for code snippets

# Menu / navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 4

