baseURL = 'https://www.liminalrecursions.com/'
languageCode = 'en-us'
title = 'Liminal Recursions'
theme = "stack"

[pagination]
pagerSize = 10

[params]
mainSections = ["posts"]
description = "Adventures in Social Anatomy"
summaryLength = 70

[params.sidebar]
emoji = "ðŸŒ€"
subtitle = "Adventures in Social Anatomy"

[params.sidebar.avatar]
enabled = true
local = true
src = "/img/avatar-small.png"

[params.footer]
since = 2025

[params.comments]
enabled = true
provider = "giscus"

[[params.widgets.homepage]]
type = "reach"

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "archives"
[params.widgets.homepage.params]
limit = 10


[params.comments.giscus]
repo = "intraventions/writing"
repoID = "R_kgDOQjxv3g"
category = "General"
categoryID = "<your-category-id>"
mapping = "pathname"
reactionsEnabled = true
emitMetadata = false
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "en"

# Menu 

# Menu 
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
params = { icon = "home" }

[[menu.main]]
identifier = "about"
name = "About"
url = "/page/about/"
weight = 2
params = { icon = "user" }

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3
params = { icon = "archives" }

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4
params = { icon = "tag" }
